[project]
name = "cli"
version = "0.1.0"
description = "Starts IPython"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.1.0",
    "mcp>=1.6.0",
    "requests>=2.32.3",
]
